package com.example.data.model

enum class PitchPerspective(val label: String, val description: String) {
    VENTURE_CAPITAL("Venture Capital (Seed / Series A)", "Optimized for VC partner meetings, deal memos, and investor presentations"),
    ENTERPRISE_BUYER("Enterprise Buyer ROI", "Focused on CFO / VP Ops business case, risk mitigation, and seamless adoption"),
    EXECUTIVE_BOARD("Executive Board Summary", "High-altitude strategic synthesis for corporate sponsors and advisory boards")
}

enum class PitchArchitectPillar(val title: String, val subtitle: String, val index: Int) {
    PROBLEM("1. Problem & Core Inefficiency", "ERP logic bottlenecks, operational waste, and legacy friction", 1),
    SOLUTION("2. Frontier Solution Architecture", "Autonomous intelligence wedge, non-invasive deployment, and throughput gains", 2),
    MARKET_OPPORTUNITY("3. Market Opportunity & Moat", "TAM/SAM/SOM expansion, beachhead ICP, and architectural defensibility", 3),
    FINANCIALS("4. Venture Financials & Economics", "Unit economics, 5-year ARR trajectory, customer ROI, and seed capital allocation", 4)
}

data class PitchSectionItem(
    val title: String,
    val narrative: String,
    val metricValue: String? = null,
    val metricLabel: String? = null,
    val tag: String? = null
)

data class PitchDeckArchitectSection(
    val pillar: PitchArchitectPillar,
    val headline: String,
    val subheadline: String,
    val executiveSummary: String,
    val items: List<PitchSectionItem>,
    val strategicTakeaway: String
)

data class SynthesizedPitchBlueprint(
    val ventureName: String,
    val tagline: String,
    val targetRaise: String,
    val perspective: PitchPerspective,
    val problemSection: PitchDeckArchitectSection,
    val solutionSection: PitchDeckArchitectSection,
    val marketSection: PitchDeckArchitectSection,
    val financialsSection: PitchDeckArchitectSection
) {
    val allSections: List<PitchDeckArchitectSection>
        get() = listOf(problemSection, solutionSection, marketSection, financialsSection)

    fun toFormattedMarkdown(): String {
        val sb = StringBuilder()
        sb.appendLine("# Pitch Deck Architect Blueprint: $ventureName")
        sb.appendLine("### $tagline")
        sb.appendLine("**Perspective Mode:** ${perspective.label} | **Target Round:** $targetRaise")
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine()

        allSections.forEach { section ->
            sb.appendLine("## ${section.pillar.title}")
            sb.appendLine("### ${section.headline}")
            sb.appendLine("*${section.subheadline}*")
            sb.appendLine()
            sb.appendLine("**Executive Synthesis:**")
            sb.appendLine(section.executiveSummary)
            sb.appendLine()
            sb.appendLine("**Key Pillar Evidence:**")
            section.items.forEach { item ->
                val metricText = if (item.metricValue != null) " [${item.metricValue} - ${item.metricLabel ?: ""}]" else ""
                sb.appendLine("- **${item.title}**$metricText: ${item.narrative}")
            }
            sb.appendLine()
            sb.appendLine("> **Strategic Takeaway:** ${section.strategicTakeaway}")
            sb.appendLine()
            sb.appendLine("---")
            sb.appendLine()
        }

        sb.appendLine("Generated by ProcessFoundry Pitch Deck Architect Engine")
        return sb.toString()
    }
}
